version: "3.8"
services:

  ssl:
    init: true
    build: ssl/.
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/live/my-remote-access.ddo.jp:/etc/nginx/my-remote-access.ddo.jp

  video-chat:
    init: true
    build: video/.
    restart: always
