# https://hub.docker.com/_/nginx
FROM nginx:latest

# RUN cat /etc/nginx/conf.d/default.conf

COPY default.conf /etc/nginx/conf.d

# RUN cat /etc/nginx/conf.d/default.conf

# COPY ssl /etc/nginx/ssl

COPY html /usr/share/nginx/html